version: '3.4'

services:
  hydronetwork:
    image: hydronetwork
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
