version: '3.4'

services:
  hydronetwork:
    build: ./frontend
    environment:
      NODE_ENV: development
    # volumes:
    #   - ./test:/usr/src/app
    #   - ./test/node_modules:/usr/src/app/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    command: npm run serve
    # entrypoint: ["ls"]
    



